global:
    resolve_timeout: 1m
route:
    group_by: ['alter_cassandra']
    receiver: 'webhook'

receivers:
    - name: 'webhook'
      webhook_configs:
      - url: http://10.0.9.243:8060/dingtalk/webhook_legacy/send  # replace with your PagerTree webhook url

inhibit_rules:
  - source_match:
      severity: 'red'
    target_match:
      severity: 'red'
    equal: ['pager', 'dev', 'instance']
