version: "2"
services:
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - "prometheus:/prometheus"
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus/tg_cassandra.json:/etc/prometheus/tg_cassandra.json"
      - "./prometheus/tg_node.json:/etc/prometheus/tg_node.json"
      - "./prometheus/tg_mysql.json:/etc/prometheus/tg_mysql.json"
      - "./prometheus/tg_es.json:/etc/prometheus/tg_es.json"
      - "./prometheus/tg_haproxy.json:/etc/prometheus/tg_haproxy.json"
      - "./prometheus/rules:/etc/prometheus/rules"
      - "/etc/localtime:/etc/localtime:ro"
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
      GF_RENDERING_SERVER_URL: http://10.0.9.243:8081/render
      GF_RENDERING_CALLBACK_URL: http://10.0.9.243:3000/
      GF_LOG_FILTERS: rendering:debug

    volumes:
      - "grafana:/var/lib/grafana"
      - "./grafana/prometheus-datasource.yaml:/etc/grafana/provisioning/datasources/prometheus-datasource.yaml"
      - "./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
      - "/etc/localtime:/etc/localtime:ro"
  alertmanager:
    image: "prom/alertmanager"
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081:8081
    environment:
      ENABLE_METRICS: 'true'
  webhook:
    image: timonwong/prometheus-webhook-dingtalk:latest
    #container_name: prometheus-webhook-alertmanagers
    hostname: webhook-alertmanagers
    restart: always
    volumes:
      - ./webhook:/etc/prometheus-webhook-dingtalk
      - ./webhook/config.yml:/etc/prometheus-webhook-dingtalk/config.yml
      - /etc/localtime:/etc/localtime
    ports:
      - "8060:8060"
  elasticsearch_exporter:
    image: justwatch/elasticsearch_exporter:latest
    command:
     - '--es.uri=http://10.0.13.134:9200'
     - '--es.all=true'
    restart: always
    ports:
     - "9113:9114"
  
  elasticsearch_exporter-1:
    image: justwatch/elasticsearch_exporter:latest
    command:
     - '--es.uri=http://10.0.13.135:9200'
    restart: always
    ports:
     - "9115:9114"

  elasticsearch_exporter-2:
    image: justwatch/elasticsearch_exporter:latest
    command:
     - '--es.uri=http://10.0.13.136:9200'
    restart: always
    ports:
     - "9116:9114"

  elasticsearch_exporter-3:
    image: justwatch/elasticsearch_exporter:latest
    command:
     - '--es.uri=http://10.0.13.171:9200'
    restart: always
    ports:
     - "9117:9114"

  elasticsearch_exporter-4:
    image: justwatch/elasticsearch_exporter:latest
    command:
     - '--es.uri=http://10.0.13.172:9200'
    restart: always
    ports:
     - "9118:9114"

volumes:
  grafana:
  prometheus:

networks:
  walle-net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.1/24
