version: "2"
services:
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - "prometheus:/prometheus"
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus/tg_cassandra.json:/etc/prometheus/tg_cassandra.json"
      - "./prometheus/tg_node.json:/etc/prometheus/tg_node.json"
      - "./prometheus/alert.rules:/etc/prometheus/alert.rules"
      - "/etc/localtime:/etc/localtime:ro"
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    volumes:
      - "grafana:/var/lib/grafana"
      - "./grafana/prometheus-datasource.yaml:/etc/grafana/provisioning/datasources/prometheus-datasource.yaml"
      - "./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
      - "/etc/localtime:/etc/localtime:ro"
  alertmanager:
    image: "prom/alertmanager"
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"

volumes:
  grafana:
  prometheus:
