global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['10.0.9.243:9093']
    scheme: http
    timeout: 10s

rule_files:
  - /etc/prometheus/rules/*.rules

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - 10.0.9.243:9090

  - job_name: "cassandra"
    scrape_interval: 15s
    scrape_timeout:  15s
    file_sd_configs:
      - files:
        - 'tg_cassandra.json'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:[0-9]*)$
        target_label: instance
        replacement: ${1}

  - job_name: "node"
    file_sd_configs:
      - files:
        - 'tg_node.json'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:[0-9]*)$
        target_label: instance
        replacement: ${1}

  - job_name: "MySQL"
    file_sd_configs:
      - files:
        - 'tg_mysql.json'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:[0-9]*)$
        target_label: instance
        replacement: ${1}
  
  - job_name: "elasticsearch"
    file_sd_configs:
      - files:
        - 'tg_es.json'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:[0-9]*)$
        target_label: instance
        replacement: ${1}
  - job_name: "haproxy"
    file_sd_configs:
      - files:
        - 'tg_haproxy.json'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:[0-9]*)$
        target_label: instance
        replacement: ${1}
  - job_name: "kafka"
    file_sd_configs:
      - files:
        - 'tg_kafka.json'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:[0-9]*)$
        target_label: instance
        replacement: ${1}
  - job_name: "redis"
    file_sd_configs:
      - files:
        - 'tg_redis.json'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:[0-9]*)$
        target_label: instance
        replacement: ${1}
