{
 "title": "C* Table Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "jobname", "label": "Job name of Cassandra exporter", "query": "${VAR_JOBNAME}" },
   {
    "name": "rate",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "query": "label_values(up{job=\"$jobname\"}, instance)"
   },
   {
    "name": "keyspace",
    "query": "label_values(cassandra_table_totaldiskspaceused{}, keyspace)"
   },
   {
    "name": "table",
    "query": "label_values(cassandra_table_totaldiskspaceused{keyspace=\"$keyspace\"}, table)"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_percentrepaired{keyspace=\"eo_chatmsg\"}",
     "legendFormat": "{{instance}}:{{table}}"
    }
   ]
  },
  {
   "title": "Write Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (irate(cassandra_table_writelatency{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"}[$rate]))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (irate(cassandra_table_writetotallatency{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"}[$rate])) / avg by (table) (irate(cassandra_table_writelatency{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"}[$rate]))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Read Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (irate(cassandra_table_readlatency{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"}[$rate]))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Key Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (irate(cassandra_table_keycachehitrate{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"}[$rate]))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (irate(cassandra_table_readtotallatency{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"}[$rate])) / avg by (table) (irate(cassandra_table_readlatency{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"}[$rate]))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Bytes Flushed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (increase(cassandra_table_bytesflushed{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"}[$rate]))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Speculative Retries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (irate(cassandra_table_speculativeretries{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"}[$rate]))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "sstable count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (cassandra_table_livesstablecount{instance=~\"$instance\",keyspace='$keyspace',table=~\"$table\"})",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Pending Compactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (cassandra_table_pendingcompactions{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"})",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Pending Flushes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (cassandra_table_pendingflushes{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"})",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Live disk space used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (cassandra_table_livediskspaceused{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"})",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Snapshot size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (cassandra_table_snapshotssize{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"})",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Bytes Flushed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (irate(cassandra_table_bytesflushed{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"}[$rate]))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "% Repaired",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (table) (cassandra_table_percentrepaired{instance=~\"$instance\",keyspace=\"$keyspace\",table=~\"$table\"})",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Est Partitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (cassandra_table_estimatedpartitioncount{instance=~\"$instance\",keyspace='$keyspace',table=~\"$table\"})",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Memtable Live Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (cassandra_table_memtablelivedatasize{instance=~\"$instance\",keyspace='$keyspace',table=~\"$table\"})",
     "legendFormat": "{{ table }}"
    }
   ]
  }
 ]
}