{
 "title": "ZooKeeper",
 "description": "Metrics about ZooKeeper Service",
 "tags": [
  "zookeeper",
  "metadata"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "{job=~\".+\"}"
   },
   {
    "name": "instance",
    "label": "zookeeper server",
    "query": "zookeeper_server_requests{job=~\"$job\", instance=~\".+\"}"
   },
   { "name": "PULSAR_CLUSTER", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "znode",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(zookeeper_server_znode_count{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "znode count"
    }
   ]
  },
  {
   "title": "watches",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(zookeeper_server_watches_count{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "ephemerals",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(zookeeper_server_ephemerals_count{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "data size",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(zookeeper_server_data_size_bytes{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "connections",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(zookeeper_server_connections{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Write Requests",
   "type": "graph",
   "description": "All write operations (create / setData / ...)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "writes / s" }
   ],
   "targets": [
    {
     "expr": "irate(zookeeper_server_requests_latency_ms_count{job=~\"$job\", instance=~\"$instance\", type=\"write\"}[30s])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Read Requests",
   "type": "graph",
   "description": "All read operations (getData / getChildren / ...)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "reads / s" }
   ],
   "targets": [
    {
     "expr": "irate(zookeeper_server_requests_latency_ms_count{job=~\"$job\", instance=~\"$instance\", type=\"read\"}[30s])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Write Latency - 99pct",
   "type": "graph",
   "description": "All write operations (create / setData / ...)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zookeeper_server_requests_latency_ms{job=~\"$job\", instance=~\"$instance\", type=\"write\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Latency - 99pct",
   "type": "graph",
   "description": "All write operations (create / setData / ...)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zookeeper_server_requests_latency_ms{job=~\"$job\", instance=~\"$instance\", type=\"read\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Throughput",
   "type": "graph",
   "description": "Request Throughput (break down by type)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(zookeeper_server_requests{job=~\"$job\", instance=~\"$instance\"}[30s])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Z-Nodes count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_server_znode_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Data set size",
   "type": "graph",
   "description": "Size of the data stored in a ZK server",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "zookeeper_server_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Number of opened connections",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_server_connections{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of watches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_server_watches_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of ephemerals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_server_ephemerals_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}